### ISSUE TITLE
Update is not working.

### ISSUE THREAD

**Issue by seangordon** [seangordon/QNAP-bliss#1]
Having bliss perform a self update does not work - bliss complains about not being able to restart itself after the update.
As a work around, simply reinstall the QPKG as this will automatically fetch the latest build of bliss and perform the upgrade. All configuration data is maintained when upgrading this way.

**Comment by gravelld** [comment]
There's inconsistency in bliss's properties here. You need to define the entire property including name, not just value:

```
export BLISS_LAUNCHER_PROPERTY="-Dbliss.launcher=${INSTALL_PATH}/bliss-runner.sh start"
```

When bliss tries to run that it should print out the output to stdout and also to the log file at INFO level.

I'm not 100% sure that will work - if it doesn't you might need to surround with a bash statement, e.g. 

```
export BLISS_LAUNCHER_PROPERTY="-Dbliss.launcher=bash ${INSTALL_PATH}/bliss-runner.sh start"
```

Also, not sure if I've got the quotes right there, feels like we need quotes to surround the second equals sign, but what about the spaces? Sorry, forgot by bash-fu there.

**Comment by crieke** [comment]
I tried to include the BLISS_LAUNCHER_PROPERTY in the bliss-runner.sh script. I had issues with the whitespace before the start argument (in ${INSTALL_PATH}/bliss-runner.sh start). As a workaround I created a new bliss-start-after-update.sh script which simply runs the bliss-runner with the start argument. This worked at first.
But then I observed that the update mechanism does not work after the initial installation. If I stop and start bliss manually, the update process (including the restart) works.
When I try to update after the installation and the initial automatic launch I get the following error:

```
Process ID 26850
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
    at java.lang.System.initProperties(Native Method)
    at java.lang.System.initializeSystemClass(System.java:1166)
```

Any ideas?

**Comment by gravelld** [comment]
Any help: http://stackoverflow.com/questions/12338233/shell-init-issue-when-click-tab-whats-wrong-with-getcwd ?

Is that the full stack trace, could you paste any more?

When you say:

> I observed that the update mechanism does not work after the initial installation

Do you mean that repeated updates do not work? E.g. 
1. install bliss
2. Update it (it restarts)
3. Update it again <- this fails

?

**Comment by crieke** [comment]
> Do you mean that repeated updates do not work? E.g.
> 
> install bliss
> Update it (it restarts)
> Update it again <- this fails
> 
> ?

I mean when bliss is running and has been started after the snap installation routine it won't update.
When it is stopped in the qnap App Center and started again, the update within bliss works.

Your link does help. I think bliss is started after the installation from a temporary installation directory, which does not exist anymore. So it is probably required to enter the INSTALL_PATH at the end of the installation routine. I will test it later.

**Comment by crieke** [comment]
Entering the INSTALL_PATH in the bliss-runner and adding the BLISS_LAUNCHER_PROPERTY solved the auto-update issue. I have put my modifications on my forked repository.

**Comment by gravelld** [comment]
Sorry, getting carried away with the emoticons there.

Worth issuing a PR?

**Comment by seangordon** [comment]
I think we can close this now :o)
