### ISSUE TITLE
Audio Fingerprinting is not working

### ISSUE THREAD

**Issue by seangordon** [seangordon/QNAP-bliss#2]
Audio Fingerprinting in Bliss requires the compilation of additional binary libraries, specificallly fpcalc  - https://acoustid.org/chromaprint
However, I have run into problems getting this to compile using the QNAP tool-chain since several of the dev tools in the tool-chain are out of date.

**Comment by gravelld** [comment]
One thing that might be of use is the way this was done on Synology: https://pcloadletter.co.uk/2012/09/17/bliss-package-for-synology/ (see "Build Notes").

**Comment by gravelld** [comment]
I added this as a request to Entware - if we have it there, we could install it using Entware, right? https://github.com/Entware-ng/Entware-ng/issues/758
