### ISSUE TITLE
Minimum Java version should be Java 7

### ISSUE THREAD

**Issue by gravelld** [seangordon/QNAP-bliss#7]
I noticed in `qpkg.cfg` that Java 6 is set as required 

```
# Specifies any packages required for the current package to operate.
QPKG_REQUIRE="JRE >= 1.6 || JRE_ARM >= 1.6"
```
https://github.com/seangordon/QNAP-bliss/blob/master/bliss/qpkg.cfg

bliss requires Java 7; its source is built with Java 7 source compatibility, plus it uses features in the core Java API which are not in Java 6.

**Comment by seangordon** [comment]
Thanks Dan, I have fixed the dependency
